- name: Setting dotfiles (bashrc)
  copy:
    src: dotfiles/bashrc
    dest: "{{ user_accounts[user.name]['home'] }}/.bashrc"
    owner: "{{ user.name }}"
    group: "{{ user_accounts[user.name]['group'] }}"
    mode: 0600

- name: Setting dotfiles (bash_profile)
  copy:
    src: dotfiles/bash_profile
    dest: "{{ user_accounts[user.name]['home'] }}/.bash_profile"
    owner: "{{ user.name }}"
    group: "{{ user_accounts[user.name]['group'] }}"
    mode: 0600

- name: Setting dotfiles (gitconfig)
  copy:
    src: dotfiles/gitconfig
    dest: "{{ user_accounts[user.name]['home'] }}/.gitconfig"
    owner: "{{ user.name }}"
    group: "{{ user_accounts[user.name]['group'] }}"
    mode: 0600

- name: Setting dotfiles (vimrc)
  copy:
    src: dotfiles/vimrc
    dest: "{{ user_accounts[user.name]['home'] }}/.vimrc"
    owner: "{{ user.name }}"
    group: "{{ user_accounts[user.name]['group'] }}"
    mode: 0600

- name: Setting dotfiles (.vim)
  unarchive:
    src: dotfiles/vim.tgz
    dest: "{{ user_accounts[user.name]['home'] }}"
    owner: "{{ user.name }}"
    group: "{{ user_accounts[user.name]['group'] }}"
