- name: Loading user account facts
  shell: "perl -e 'use strict; my $users = {}; while(my @user = getpwent()) { $users->{$user[0]} = { qq[name] => $user[0], qq[uid] => $user[2], qq[group] => scalar(getgrgid($user[3])), qq[gid] => $user[3], qq[home] => $user[7] } }; my $output = qq[{]; while(my($key,$value) = each(%{$users})) { $output .= qq[\"$key\":{]; while(my($kkey,$vvalue) = each(%{$value})) { $output .= qq[\"$kkey\":\"$vvalue\",]; }; chop($output); $output .= qq[},]; }; chop($output); $output .= qq[}]; print \"$output\n\";'"
  register: user_accounts_raw

- name: Setting user account facts
  set_fact:
    user_accounts: "{{ user_accounts_raw.stdout }}"

- name: debug
  debug: var=user_accounts


