- name: Creating groups
  group:
    name: "{{ user.group }}"
    gid: "{{ user.gid }}"
  loop: "{{ core_users }}"
  loop_control:
    loop_var: user
  when: user.group is defined

- name: Creating users
  user:
    name: "{{ user.name }}"
    group: "{{ user.group|default(omit) }}"
    uid: "{{ user.uid|default(omit) }}"
    shell: "{{ user.shell|default('/bin/bash') }}"
    state: "{{ user.state|default('present') }}"
  loop: "{{ core_users }}"
  loop_control:
    loop_var: user

- include_tasks: facts.yml

- include_tasks: dotfiles.yml
  loop: "{{ core_users }}"
  loop_control:
    loop_var: user
  when: user.dotfiles is defined and user.dotfiles
