- name: Install docker
  package:
    name: docker-ce
    state: present

- name: Enable docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Set docker group members
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ service_docker.users }}"
  when: service_docker is defined and service_docker.users is defined
